import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { styled } from "../stitches.config";
import { useTheme } from "next-themes";

const Box = styled("div", {
  boxSizing: "border-box",
});

const Button = styled("button", {
  backgroundColor: "$foreground",
  color: "$background",
  borderRadius: "9999px",
  fontSize: "13px",
  p: "10px 15px",
  "&:hover": {
    backgroundColor: "lightgray",
  },
});

const Home: NextPage = () => {
  const [mounted, setMounted] = useState(false);
  const { theme, setTheme, resolvedTheme } = useTheme();

  useEffect(() => setMounted(true), []);

  if (!mounted) return null;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button>Button</Button>
        <Box css={{ display: "inline-block" }}>
          {theme !== undefined && (
            <select value={theme} onChange={(e) => setTheme(e.target.value)}>
              <option value="dark">Dark Theme</option>
              <option value="light">Light Theme</option>
              <option value="system">System Theme</option>
            </select>
          )}
        </Box>
      </main>
    </div>
  );
};

export default Home;
